<a href="https://colab.research.google.com/github/SR2090/Linear_Regression_Using_Keras/blob/main/LRKeras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# The purpose of the training 

- Understanding how to build models using keras
- Implementing Linear Regression

What is Linear Regression ?
Linear Regression is a linear relationship model between two variables x and y where x is an independent variable, y is the dependent variable.
X is normally referred to as the Sample
Y is reffered to as Target
We want to find a straight line that will fit the model in a way that the mean square error distance from each of those points to the line is a minimum. 
Once such a line is acheived we can predict corresponding y variable to each x using that line

"We want to find the slope of the line with the least error. Once, we are able to model the given data points, we can predict the value on y axis, for a new point on x axis."

The purpose of the training is to predict house prices. This is done by finding the weights (w0 to w12) and the biases for which the network produces the correct output

Result:
- The network will be trained if the error between the predicted output and the ground truth becomes very low and doesn't decrease any further.
- About the dataset
  - https://www.cs.toronto.edu/~delve/data/boston/bostonDetail.html

Process:
- Use Sequentail class to create a Sequential Model from which we craete the Network Graph
- A dense layer is for the number of input is equal to the number of features in the data set(13) and get a single output (price)
- --------------------------------------------------------------

In [1]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.datasets import boston_housing

# Sample points
(X_train, Y_train) , (X_test, Y_test) = boston_housing.load_data()

print("Training set size: ", X_train.shape)
print("Test set size: ", X_test.shape)
print("Training example features: ", X_train[0,:])
print("Training example output: ", Y_train[0])

57344/57026 [==============================] - 0s 0us/step
Training set size:  (404, 13)
Test set size:  (102, 13)
Training example features:  [  1.23247   0.        8.14      0.        0.538     6.142    91.7
   3.9769    4.      307.       21.      396.9      18.72   ]
Training example output:  15.2


In [2]:
# The 13 features 
nfeatures = X_train.shape[1]

In [3]:
nfeatures

13

 Here we will create the model

In [6]:
# Initiate the model class type here sequential
model = Sequential()
# First Hiddent Layer
model.add(Dense(1, input_shape=(nfeatures,), activation='linear'))
# Compiling the parameters 
# Loss is mean squared error as it is a regression problem
# Optimizer 
# Controls how the network weights, biases or parameters are updated
# Loss
# How to penalize the network
# Metric
# The metrics that we want to evaluate during training and testing
model.compile(optimizer='rmsprop', loss = 'mse', metrics = ['mse', 'mae'])


In [7]:
import tensorflow as tf
print(tf.__version__)

2.3.0


In [8]:
# 14 parameters ?
# 13 for weights 
# 1 for bias
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 1)                 14        
Total params: 14
Trainable params: 14
Non-trainable params: 0
_________________________________________________________________


Here we will train the model

In [13]:
# To see detail output, change verbose to True
# Here we will train the data
model.fit(X_train, Y_train, batch_size=6, epochs=500, verbose=True)

Epoch 1/500
68/68 [==============================] - 0s 3ms/step - loss: 25.6596 - mse: 25.6596 - mae: 3.5160
Epoch 2/500
68/68 [==============================] - 0s 3ms/step - loss: 25.9639 - mse: 25.9639 - mae: 3.5103
Epoch 3/500
68/68 [==============================] - 0s 2ms/step - loss: 25.9545 - mse: 25.9545 - mae: 3.5582
Epoch 4/500
68/68 [==============================] - 0s 3ms/step - loss: 25.9107 - mse: 25.9107 - mae: 3.4540
Epoch 5/500
68/68 [==============================] - 0s 2ms/step - loss: 25.7603 - mse: 25.7603 - mae: 3.5366
Epoch 6/500
68/68 [==============================] - 0s 2ms/step - loss: 25.9142 - mse: 25.9142 - mae: 3.4553
Epoch 7/500
68/68 [==============================] - 0s 2ms/step - loss: 25.2929 - mse: 25.2929 - mae: 3.4807
Epoch 8/500
68/68 [==============================] - 0s 2ms/step - loss: 25.5961 - mse: 25.5961 - mae: 3.4855
Epoch 9/500
68/68 [==============================] - 0s 2ms/step - loss: 25.9065 - mse: 25.9065 - mae: 3.5425
Epoch 10/5

Inference from the given model

In [14]:
# This is for calculating the loss for test set data
model.evaluate(X_test, Y_test, verbose=True)

4/4 [==============================] - 0s 2ms/step - loss: 27.5576 - mse: 27.5576 - mae: 3.8968


[27.557592391967773, 27.557592391967773, 3.8967504501342773]

In [12]:
# To find output using our train model
Y_pred = model.predict(X_test)
# Comparing predicted with test sample
print(Y_test[:5])
print(Y_pred[:5,0])

[ 7.2 18.8 19.  27.  22.2]
[10.148695 20.3457   22.700144 31.388618 25.04748 ]


In [15]:
# The hyper parameter epoch = 500 
# batch size is 5
# To find output using our train model
Y_pred = model.predict(X_test)
# Comparing predicted with test sample
print(Y_test[:5])
print(Y_pred[:5,0])

[ 7.2 18.8 19.  27.  22.2]
[ 7.098922 17.010742 20.300259 28.322706 22.592415]
